=== mesur-io/traceability-vocab/schemas/CertifidMillTestReportCredential.json
{
  "$id": "https://w3id.org/traceability/schemas/CertifidMillTestReportCredential.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"CertifidMillTestReportCredential\", \"@id\": \"https://w3id.org/traceability#CertifidMillTestReportCredential\"}",
  "title": "Certified Mill Test Report Verifiable Credential",
  "description": "Certifications made by a manufacturer of a metal product.",
  "type": "object",
  "properties": {
      "@context": {
        "type": "array"
      },
      "type": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "array"
          }
        ]
      },
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "issuanceDate": {
        "type": "string"
      },
      "issuer": {
        "type": "object"
      },
      "credentialSubject": {
        "type": "object"
      },
      "proof": {
        "type": "object"
      },
      "relatedLink": {
        "$comment": "{\"term\": \"relatedLink\", \"@id\": \"https://w3id.org/traceability#LinkRole\"}",
        "title": "Related Link",
        "description": "Links related to this verifiable credential",
        "type": "array",
        "items": {
          "$ref": "https://w3id.org/traceability/schemas/LinkRole.json"
        }
      }
    },
  "additionalProperties": false,
  "required": ["proof"],
  "examples": []
}

=== mesur-io/traceability-vocab/docs/credentials/EcommerceProductRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommerceProductRegistrationCredential",
    "productCode": 14,
    "productCodeType": "GTIN",
    "certificateName": "ACME Ecommerce Product Registration Credential"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-24T21:34:58.884Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..7uqXwcLt0qUi5R-Nyervw3MhUYBEeb59JhVhOBkda2TQ_6R6MA8eTvE_wIOLhB3U9P0_zycZQ8tJ_Cy99SsEAQ",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/credentials/CrudeOilProduct.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "http://example.com/credentials/3a185b8f-078a-4646-8343-76a45c2856a5",
  "type": [
    "VerifiableCredential"
  ],
  "issuer": {
    "id": "did:example:123",
    "type": [
      "Organization"
    ],
    "url": "https://example.com/organizations/3a185b8f-078a-4646-8343-76a45c2856ad",
    "name": "Crude Oil Producer"
  },
  "issuanceDate": "2020-04-09T21:12:12Z",
  "credentialSubject": {
    "id": "did:examle:123",
    "type": "CrudeOilProduct",
    "HSCode": "270900",
    "UWI": "100.12-04-091-05-W5.00",
    "productionDate": "2020-03-30",
    "facility": {
      "type": "Place",
      "address": {
        "type": "PostalAddress",
        "organizationName": "Example Crude Producer",
        "addressRegion": "Edmonton",
        "addressCountry": "Canada"
      },
      "geo": {
        "type": "GeoCoordinates",
        "latitude": "53.5461",
        "longitude": "113.4938"
      }
    },
    "product": {
      "type": "Product",
      "name": "Heavy Sour Dilbit",
      "sizeOrAmount": {
        "type": "MeasuredValue",
        "unitCode": "bbl",
        "value": "10000"
      },
      "description": "Crude oil stream, produced from diluted bitumen."
    },
    "observation": [
      {
        "type": "Observation",
        "property": {
          "type": "MechanicalProperty",
          "name": "api Gravity"
        },
        "measurement": {
          "type": "MeasuredValue",
          "unitCode": "test",
          "value": "21"
        }
      },
      {
        "type": "Observation",
        "property": {
          "type": "MechanicalProperty",
          "name": "viscosityAt10C"
        },
        "measurement": {
          "type": "MeasuredValue",
          "unitCode": "test",
          "value": "302"
        }
      }
    ]
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-03-02T20:37:27.382Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..9cd9MXvkZ_cRedSE2vdvCfEV9iFDr121SASZazTSAcbUJNLQ8bPKUeFVSO4QkHdr1yWnTz4D9QH39gX6qfq7Aw",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/credentials/EcommercePackageRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommerceWayBillRegistrationCredential",
    "wayBillID": "ACMEWayBill#375",
    "carrierName": "Zemlak Inc",
    "modeOfTransport": "Truck",
    "portOfEntry": {
      "type": "ShippingStop",
      "shippingStopAddress": {
        "type": "PostalAddress",
        "organizationName": "Moore - Jacobs",
        "streetAddress": "02932 Schaden Locks",
        "addressLocality": "Codybury",
        "addressRegion": "Montana",
        "postalCode": "54086-6140",
        "addressCountry": "American Samoa"
      },
      "carrier": {
        "type": "Organization",
        "name": "Leannon - Durgan",
        "description": "Optimized local collaboration",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "330 Paucek Corner",
          "addressLocality": "South Marjorieland",
          "addressRegion": "New Mexico",
          "postalCode": "80193",
          "addressCountry": "Equatorial Guinea"
        },
        "email": "Wade.Spinka93@example.org",
        "phoneNumber": "555-264-6962",
        "faxNumber": "555-779-3805"
      },
      "vesselNumber": "ACMECarrierVessel#401",
      "arrivalDate": "2-1-2021",
      "stopType": "Stopover"
    },
    "masterWayBill": "No",
    "wayBillVCID": [
      "https://vc.example.com/?queryID=0xFcFFC16684C56a38c8ECfEc124deF735b6D7ACf3ff7c66B9B5DdE1b0bdB4e1f8"
    ],
    "packageVCID": [
      "https://vc.example.com/?queryID=0xfE71c4b0F7C8A5bCc7F6db636B310F9A84600B4ffABAd1E7e2ECCd972186e7eA",
      "https://vc.example.com/?queryID=0xde6Dca82FfCAfc5A5a0bf9209240Dea6cbfD35d9bA45E1d6f3DEdB6d2DaB449D",
      "https://vc.example.com/?queryID=0xDb7B2D76D255e90B7C603bb9a4f2575E374bcf871F5F55faf636F05dFb91067D",
      "https://vc.example.com/?queryID=0xd5e3ba9Fc5de1A855AB8adFd8bB1BC37b4f0Cc7e40fbB47e23Ef88bEC3e7A24E",
      "https://vc.example.com/?queryID=0xbDf55e3BFcbb55F2FDcDDd4767ffCDCD8BDeC1E3BDedc082EeF0636caf9eF43f",
      "https://vc.example.com/?queryID=0x05a73A8eACfe6cb2b8d555cFF8aDDd9B7beceaD45fa6c0Ae03FEaE6ED8A0EE79"
    ],
    "certificateName": "ACME Carrier Ecommerce Way Bill Registration Certificate"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-03-02T20:37:11.778Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..s1S0230zCwMN2OObxTU8cbNkM09P2CL3MnVy7OvNmMGojGc6TwBJhqYUc5NH_C34mSysWcTQgULXkyyWVaYFDg",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/docs/credentials/LegalEntityIdentifierCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "LegalEntityIdentifierCredential",
    "leiCode": "7VAZV6PSUDBD4F2P3ON6",
    "certificateName": "US Legal Entity Certificate"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-25T17:30:10.248Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TzEFYcw3RPbjYxC2wHfHTslmlMTJNnx0O2njFABeG6TYr7WzsJfcAIkFLn-OaGRfFb_VwXnUp69TA6XyrKF9AQ",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/docs/credentials/EcommercePackingListRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommercePackingListRegistrationCredential",
    "packageItems": [
      {
        "type": "EcommercePackingListItem",
        "orderID": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
        "productInOrder": [
          "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58599e"
        ]
      }
    ],
    "certificateName": "ACME Ecommerce Packing List Registration Credential"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-25T17:11:24.394Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..CLDYKjulIkZtba1Mid_tZApscOFoSdzGXvkXWmK67qECet1OrOg-P8ZE3RoDVBy9wes6LnHNH7fyT5kabidKBg",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/credentials/EcommerceProductReceiptRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acmecarrier.com",
    "type": "EcommerceProductReceiptRegistrationCredential",
    "receiptID": "Receipt#626",
    "packingListID": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a"
    ],
    "orderID": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a"
    ],
    "productInOrder": [
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
    ],
    "certificateName": "ACME Carrier Ecommerce Product Receipt Registration Certificate"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-03-02T20:37:04.117Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..w6Ijjsy_8OZWB0BJFDukA1Rl5NzqVjHvl9MK_YgycHUyDjdll02Q2c4bdJelbEC707akGhuPqzznuUNzbCLsBg",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/credentials/EcommerceOrderRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommerceOrderRegistrationCredential",
    "orderID": "Order#897",
    "productInOrder": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
    ],
    "certificateName": "ACME Ecommerce Order Registration Credential"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-03-02T20:37:09.005Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..Q-bUyWqZ2iH2l256Kp06NCXSe0BNwTOZnVfIQJlOLJyC6LMpJvAexKL3jtwjGCfBHzPbM04ejVcXlcbnRNajAQ",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/credentials/EcommerceInvoiceRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommerceInvoiceRegistrationCredential",
    "invoiceID": "Invoice#213",
    "orderID": [
      "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a"
    ],
    "productInOrder": [
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
      "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
    ],
    "certificateName": "ACME Ecommerce Invoice Registration Credential"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-03-02T20:37:07.254Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..sK-MO5FAaKlGgGhwoJ52XOdhniG3H_O5WddCBDzvwLRtII_ct6csiPnmWVbA1hZmYe6pl9zCZippIBq4qZ87CA",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}
