=== mesur-io/traceability-vocab/schemas/CertifidMillTestReportCredential.json
{
  "$id": "https://w3id.org/traceability/schemas/CertifidMillTestReportCredential.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"CertifidMillTestReportCredential\", \"@id\": \"https://w3id.org/traceability#CertifidMillTestReportCredential\"}",
  "title": "Certified Mill Test Report Verifiable Credential",
  "description": "Certifications made by a manufacturer of a metal product.",
  "type": "object",
  "properties": {
      "@context": {
        "type": "array"
      },
      "type": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "array"
          }
        ]
      },
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "issuanceDate": {
        "type": "string"
      },
      "issuer": {
        "type": "object"
      },
      "credentialSubject": {
        "type": "object"
      },
      "proof": {
        "type": "object"
      },
      "relatedLink": {
        "$comment": "{\"term\": \"relatedLink\", \"@id\": \"https://w3id.org/traceability#LinkRole\"}",
        "title": "Related Link",
        "description": "Links related to this verifiable credential",
        "type": "array",
        "items": {
          "$ref": "https://w3id.org/traceability/schemas/LinkRole.json"
        }
      }
    },
  "additionalProperties": false,
  "required": ["proof"],
  "examples": []
}

=== mesur-io/traceability-vocab/docs/credentials/EcommercePackageRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1",
    {
      "productReceiptID": "https://w3id.org/traceability#EcommerceProductReceiptRegistrationCredential#receiptID"
    },
    {
      "packingListID": "https://schema.org/identifier"
    },
    {
      "orderNumber": "https://schema.org/orderNumber"
    },
    {
      "productInOrder": "https://schema.orgproductID"
    }
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.fedex.com",
    "type": "EcommercePackageRegistrationCredential",
    "trackingID": "900974216335",
    "packageItems": [
      {
        "productReceiptID": "https://example.VC_url.com/?queryID=0xA40AEf4b6EdCaD9821b0bF2d483F74BcbBD8EbCe3DE1bB4FE0dEf1AFcfcacdB9",
        "packingListID": "https://example.VC_url.com/?queryID=0xa97ABE64Fbca10F8aFdC9af16FafeBaD4B5AE28b0AFCeCFADe7cbB3d21Ace4fD",
        "orderNumber": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
        "productInOrder": [
          "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a"
        ]
      }
    ],
    "certificateName": "Fedex Ecommerce Package Registration Credential"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-24T21:34:58.023Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..jYqkOpSL_xSc4t_2-Bou_tRSWHsvCPrGTUGj79ZyTAtIsk6ygMtyaGj0aauSqhzgQRwb5vGJkpNZlWoslR6ZDA",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}

=== mesur-io/traceability-vocab/docs/credentials/EcommerceAdditionalProductCodeRegistrationCredential.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credentials/123",
  "type": [
    "VerifiableCredential"
  ],
  "issuanceDate": "2021-02-04T20:29:37+00:00",
  "issuer": {
    "id": "did:example:123"
  },
  "credentialSubject": {
    "id": "did:web:www.acme.com",
    "type": "EcommerceAdditionalProductCodeRegistrationCredential",
    "productVCid": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
    "addProductCode": 30977065546903,
    "addProductCodeType": "CO",
    "certificateName": "ACME Ecommerce Country of Origin Code Product Registration Certificate"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2021-02-24T21:34:59.307Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..b02QSXByPtWlM3OxSxwbqhpJ-uG2Frm-efiudYOew_YeEQP_OsvuhGBW8mxLMLzvKhiovVF4VPRrenIIR36ZBw",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:123#key-0"
  }
}
